# Generated by Django 5.1.0

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassEnvelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vref_i', models.FloatField(default=50.0, help_text='Vref for Class I (m/s)')),
                ('vref_ii', models.FloatField(default=42.5, help_text='Vref for Class II (m/s)')),
                ('vref_iii', models.FloatField(default=37.5, help_text='Vref for Class III (m/s)')),
                ('iref_a_plus', models.FloatField(default=0.18, help_text='Iref for A+')),
                ('iref_a', models.FloatField(default=0.16, help_text='Iref for A')),
                ('iref_b', models.FloatField(default=0.14, help_text='Iref for B')),
                ('iref_c', models.FloatField(default=0.12, help_text='Iref for C')),
                ('vave_over_vref', models.FloatField(default=0.2, help_text='Vave/Vref ratio')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_envelope', to='projects.project')),
            ],
            options={
                'verbose_name': 'Class Envelope',
                'verbose_name_plural': 'Class Envelopes',
            },
        ),
    ]
