# Generated by Django 5.1.0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('climate', '0001_initial'),
        ('projects', '0001_initial'),
        ('sites', '0001_initial'),
        ('turbines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('edition', models.CharField(choices=[('ed3', 'Edition 3'), ('ed4', 'Edition 4')], default='ed4', max_length=10)),
                ('class_envelope_snapshot', models.JSONField(help_text='Snapshot of ClassEnvelope at assessment time')),
                ('overall_status', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Warn', 'Warn'), ('Fail', 'Fail')], max_length=10, null=True)),
                ('flags', models.JSONField(blank=True, default=list, help_text='Overall assessment flags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='projects.project')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='sites.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentTurbine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved_vref_mps', models.FloatField(help_text='Resolved Vref (m/s)')),
                ('resolved_iref', models.FloatField(help_text='Resolved Iref')),
                ('resolved_vave_mps', models.FloatField(help_text='Resolved design Vave (m/s)')),
                ('cct', models.FloatField(help_text='Complexity correction factor (1.00 or 1.15)')),
                ('apply_density_to_v50', models.BooleanField(default=False, help_text='Apply density correction to V50 in extreme wind check')),
                ('wohler_exponents', models.JSONField(blank=True, default=list, help_text='Damage equivalent exponents [m1, m2, ...]')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_turbines', to='assessments.assessment')),
                ('hub_climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate.hubclimate')),
                ('turbine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turbines.turbine')),
            ],
            options={
                'unique_together': {('assessment', 'turbine')},
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.CharField(choices=[('extreme_wind', 'Extreme Wind'), ('wind_distribution', 'Wind Distribution'), ('turbulence_ntm', 'Turbulence NTM'), ('shear', 'Shear'), ('inflow', 'Inflow'), ('air_density', 'Air Density'), ('complexity', 'Complexity')], max_length=30)),
                ('status', models.CharField(choices=[('Pass', 'Pass'), ('Warn', 'Warn'), ('Fail', 'Fail')], max_length=10)),
                ('value', models.FloatField(blank=True, help_text='Check value', null=True)),
                ('limit', models.FloatField(blank=True, help_text='Check limit', null=True)),
                ('units', models.CharField(blank=True, max_length=50)),
                ('detail', models.JSONField(blank=True, default=dict, help_text='Additional check details')),
                ('flags', models.JSONField(blank=True, default=list, help_text='Check-specific flags')),
                ('assessment_turbine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='assessments.assessmentturbine')),
            ],
            options={
                'ordering': ['assessment_turbine', 'check_id'],
                'unique_together': {('assessment_turbine', 'check_id')},
            },
        ),
    ]
