# Generated by Django 5.1 on 2026-08-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkresult',
            name='check_id',
            field=models.CharField(choices=[('extreme_wind', 'Extreme Wind'), ('wind_distribution', 'Wind Distribution'), ('turbulence_ntm', 'Turbulence NTM'), ('turbulence_ieff', 'Effective Turbulence (Ieff)'), ('shear', 'Shear'), ('inflow', 'Inflow'), ('air_density', 'Air Density'), ('complexity', 'Complexity')], max_length=30),
        ),
    ]
