# Generated by Django 5.1.0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WtgModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('rotor_d_m', models.FloatField(help_text='Rotor diameter (m)')),
                ('hub_height_default_m', models.FloatField(help_text='Default hub height (m)')),
                ('v_in_mps', models.FloatField(help_text='Cut-in wind speed (m/s)')),
                ('v_rated_mps', models.FloatField(help_text='Rated wind speed (m/s)')),
                ('v_out_mps', models.FloatField(help_text='Cut-out wind speed (m/s)')),
                ('default_speed_class', models.CharField(choices=[('I', 'Class I'), ('II', 'Class II'), ('III', 'Class III'), ('S', 'Class S')], default='II', max_length=5)),
                ('default_ti_category', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('S', 'S')], default='B', max_length=5)),
                ('ct_status', models.CharField(choices=[('ok', 'OK'), ('missing', 'Missing'), ('suspect', 'Suspect')], default='missing', max_length=10)),
            ],
            options={
                'verbose_name': 'WTG Model',
                'verbose_name_plural': 'WTG Models',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PowerCurvePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_mps', models.FloatField(help_text='Wind speed (m/s)')),
                ('p_kw', models.FloatField(help_text='Power output (kW)')),
                ('wtg_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_curve_points', to='turbines.wtgmodel')),
            ],
            options={
                'ordering': ['wtg_model', 'v_mps'],
                'unique_together': {('wtg_model', 'v_mps')},
            },
        ),
        migrations.CreateModel(
            name='CtCurvePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_mps', models.FloatField(help_text='Wind speed (m/s)')),
                ('ct', models.FloatField(help_text='Thrust coefficient')),
                ('wtg_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ct_curve_points', to='turbines.wtgmodel')),
            ],
            options={
                'ordering': ['wtg_model', 'v_mps'],
                'unique_together': {('wtg_model', 'v_mps')},
            },
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='sites.site')),
            ],
            options={
                'ordering': ['site', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Turbine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.CharField(help_text='Unique ID within layout (e.g., T01)', max_length=50)),
                ('role', models.CharField(choices=[('new_scored', 'New (scored)'), ('existing_wake_source', 'Existing (wake source)')], default='new_scored', max_length=30)),
                ('x_m', models.FloatField(help_text='Easting in site CRS (m)')),
                ('y_m', models.FloatField(help_text='Northing in site CRS (m)')),
                ('z_base_m', models.FloatField(help_text='Base elevation (m)')),
                ('hub_height_m', models.FloatField(help_text='Hub height above base (m)')),
                ('rotor_d_m', models.FloatField(help_text='Rotor diameter (m)')),
                ('speed_class_override', models.CharField(blank=True, choices=[('I', 'Class I'), ('II', 'Class II'), ('III', 'Class III'), ('S', 'Class S')], help_text="Override model's default speed class", max_length=5, null=True)),
                ('ti_category_override', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('S', 'S')], help_text="Override model's default TI category", max_length=5, null=True)),
                ('curtailment_json', models.JSONField(blank=True, help_text='Optional curtailment settings', null=True)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turbines', to='turbines.layout')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='turbines.wtgmodel')),
            ],
            options={
                'ordering': ['layout', 'local_id'],
                'unique_together': {('layout', 'local_id')},
            },
        ),
    ]
