# Generated by Django 5.1.0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        ('turbines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteoMast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('x_m', models.FloatField(help_text='Easting in site CRS (m)')),
                ('y_m', models.FloatField(help_text='Northing in site CRS (m)')),
                ('z_base_m', models.FloatField(help_text='Base elevation (m)')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meteo_masts', to='sites.site')),
            ],
            options={
                'ordering': ['site', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MeteoHeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_m', models.FloatField(help_text='Height above base (m)')),
                ('has_wind_speed', models.BooleanField(default=True)),
                ('has_wind_direction', models.BooleanField(default=False)),
                ('has_ti', models.BooleanField(default=False)),
                ('mast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heights', to='climate.meteomast')),
            ],
            options={
                'ordering': ['mast', 'height_m'],
                'unique_together': {('mast', 'height_m')},
            },
        ),
        migrations.CreateModel(
            name='MeteoSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(upload_to='meteo_series/')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('duration_lt_1y', models.BooleanField(default=False)),
                ('not_integer_years', models.BooleanField(default=False)),
                ('recovery_lt_90', models.BooleanField(default=False)),
                ('timestep_ne_10min', models.BooleanField(default=False)),
                ('no_ti', models.BooleanField(default=False)),
                ('height_ne_hub', models.BooleanField(default=False)),
                ('height', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='climate.meteoheight')),
            ],
            options={
                'verbose_name_plural': 'Meteo series',
            },
        ),
        migrations.CreateModel(
            name='HubClimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('period_hours', models.FloatField(default=8760, help_text='Period length (hours)')),
                ('bin_width_mps', models.FloatField(help_text='Wind speed bin width (m/s)')),
                ('rho_kgm3', models.FloatField(default=1.225, help_text='Air density (kg/m³)')),
                ('v50_mps', models.FloatField(help_text='50-year extreme wind speed (m/s)')),
                ('shear_alpha', models.FloatField(blank=True, help_text='Omni-directional shear exponent', null=True)),
                ('inflow_angle_deg', models.FloatField(blank=True, help_text='Omni-directional inflow angle (deg)', null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_climates', to='sites.site')),
                ('turbine', models.ForeignKey(blank=True, help_text='Optional specific turbine', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hub_climates', to='turbines.turbine')),
            ],
            options={
                'ordering': ['site', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TiBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_center_mps', models.FloatField(help_text='Bin center wind speed (m/s)')),
                ('hours', models.FloatField(help_text='Hours in this bin')),
                ('mean_sigma_mps', models.FloatField(help_text='Mean standard deviation (m/s)')),
                ('std_sigma_mps', models.FloatField(blank=True, help_text='Std dev of sigma (null → COV=0.3 flag)', null=True)),
                ('shear_alpha_override', models.FloatField(blank=True, help_text='Per-bin shear override', null=True)),
                ('inflow_angle_deg_override', models.FloatField(blank=True, help_text='Per-bin inflow override', null=True)),
                ('hub_climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ti_bins', to='climate.hubclimate')),
            ],
            options={
                'ordering': ['hub_climate', 'v_center_mps'],
                'unique_together': {('hub_climate', 'v_center_mps')},
            },
        ),
        migrations.CreateModel(
            name='SectorWeibull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_from_deg', models.FloatField(help_text='Sector start (deg)')),
                ('sector_to_deg', models.FloatField(help_text='Sector end (deg)')),
                ('frequency', models.FloatField(help_text='Sector frequency [0,1]')),
                ('A', models.FloatField(help_text='Weibull scale parameter')),
                ('k', models.FloatField(help_text='Weibull shape parameter')),
                ('hub_climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_weibulls', to='climate.hubclimate')),
            ],
            options={
                'ordering': ['hub_climate', 'sector_from_deg'],
            },
        ),
    ]
