# Generated by Django 5.1.0

from django.db import migrations, models
import django.contrib.gis.db.models.fields
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('center_lon_deg', models.FloatField(help_text='Center longitude (EPSG:4326)')),
                ('center_lat_deg', models.FloatField(help_text='Center latitude (EPSG:4326)')),
                ('utm_zone', models.IntegerField(editable=False)),
                ('utm_north', models.BooleanField(editable=False)),
                ('crs_epsg', models.IntegerField(editable=False, help_text='UTM CRS EPSG code')),
                ('default_complexity', models.CharField(choices=[('simple', 'Simple'), ('complex', 'Complex')], default='simple', help_text='Default terrain complexity for CCT calculation', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ElevationDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('grid', 'Grid'), ('contours', 'Contours')], max_length=20)),
                ('source_label', models.CharField(help_text='e.g., SRTM, ASTER, custom survey', max_length=200)),
                ('vertical_datum', models.CharField(blank=True, max_length=100)),
                ('is_surface_not_dtm', models.BooleanField(default=True, help_text='True if source matches srtm|aster|dsm|surface')),
                ('coverage_radius_target_m', models.FloatField(default=7000)),
                ('coverage_ok', models.BooleanField(default=False)),
                ('coverage_note', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elevation_datasets', to='sites.site')),
            ],
            options={
                'ordering': ['site', 'kind', 'source_label'],
            },
        ),
        migrations.CreateModel(
            name='ElevationGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_x', models.FloatField(help_text='Origin X in site CRS (m)')),
                ('origin_y', models.FloatField(help_text='Origin Y in site CRS (m)')),
                ('dx', models.FloatField(help_text='Cell width (m)')),
                ('dy', models.FloatField(help_text='Cell height (m)')),
                ('nrows', models.IntegerField()),
                ('ncols', models.IntegerField()),
                ('nodata_value', models.FloatField(blank=True, null=True)),
                ('geotiff_file', models.FileField(upload_to='elevation_grids/')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grids', to='sites.elevationdataset')),
            ],
        ),
        migrations.CreateModel(
            name='ElevationContour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z_m', models.FloatField(help_text='Elevation (m)')),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(help_text='Contour line geometry', srid=4326)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contours', to='sites.elevationdataset')),
            ],
        ),
        migrations.CreateModel(
            name='RoughnessDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_z0_m', models.FloatField(default=0.03, help_text='Background roughness length (m), product default not IEC')),
                ('coverage_radius_m', models.FloatField(default=20000)),
                ('coverage_ok', models.BooleanField(default=False)),
                ('coverage_note', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roughness_datasets', to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='RoughnessPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('z0_m', models.FloatField(help_text='Roughness length (m)')),
                ('class_label', models.CharField(blank=True, help_text='Optional land class label', max_length=100)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygons', to='sites.roughnessdataset')),
            ],
        ),
        migrations.CreateModel(
            name='RoughnessLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('z0_left_m', models.FloatField(help_text='Roughness length on left side (m)')),
                ('z0_right_m', models.FloatField(help_text='Roughness length on right side (m)')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sites.roughnessdataset')),
            ],
        ),
    ]
